/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Problem Description
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * */
 
package projecteuler;

/**
 *
 * @author Atif
 */
/*I estimate that I had written about 3 million lines
 of assembler code in my whole life. Now, code only
 when strictly necessary.

Phi (golden ratio) is the approximate ratio between
 two consecutive terms in a Fibonacci sequence.
The ratio between consecutive even terms approaches
 phi^3 (4.236068) because each 3rd term is even.
Use a calculator and round the results to the nearest
 integer when calculating the next terms:

 2,8,34,.. multiplying by 4.236068 each time: 144,610,
 2584,10946,46368,196418 & 832040

The sum is 1089154

My codeless regards,
Rudy.*/



public class Problem2 {
    
    static double solution1 () {
        
        int cur = 2;
        int sum = 0;
        while (cur <= 4000000) {
            sum += cur * 4.236068;
            cur *= cur * 4.236068;  
            
        }
        return sum;

    }
    /*public static void main(String[] args) {
        int terget = 4000000;
        int prev = 1,temp, count = 0;
        int cur = 1;
        int ans = 0;
        
        while(cur <= terget) {
            temp = cur;
            cur = cur + prev;
            prev = temp;
   
            if(cur % 2 == 0) {
                ans += cur;
            }
            System.out.println(count);
            count++;
        }
        double ans = solution1();
        System.out.println(ans);
    }*/
}
